import Header from '@/components/navigation/header';
import './globals.css';
import EdgeSocial from '@/components/navigation/edge-social';
import Footer from '@/components/navigation/footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <EdgeSocial />
        {children}
        <Footer />
      </body>
    </html>
  );
}
